-- H2 内存库建表脚本（列名与生产 MySQL 库保持一致，语法按 H2 2.x 调整）
-- 差异说明：
--   1) MySQL 的 `ON UPDATE CURRENT_TIMESTAMP` H2 不支持，已移除；
--   2) 行内 `UNIQUE KEY xxx (col)` / `INDEX idx (col)` H2 不支持，改为 CONSTRAINT / 独立 CREATE INDEX；
--   3) `TINYINT(1)` 显示宽度 H2 不支持，统一为 TINYINT；
--   4) 自增主键使用 H2 标准写法 GENERATED BY DEFAULT AS IDENTITY，便于显式插入固定 ID。

DROP TABLE IF EXISTS icps_student_course;
DROP TABLE IF EXISTS icps_course;
DROP TABLE IF EXISTS icps_teacher;
DROP TABLE IF EXISTS icps_stu;
DROP TABLE IF EXISTS icps_user;

-- 用户认证表
CREATE TABLE icps_user (
    user_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL,
    password     VARCHAR(100) NOT NULL,
    role         VARCHAR(20)  NOT NULL DEFAULT 'student',
    status       INT          DEFAULT 1,
    deleted      TINYINT      NOT NULL DEFAULT 0,
    last_login   TIMESTAMP    DEFAULT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_username UNIQUE (username)
);
CREATE INDEX idx_user_role ON icps_user (role);

-- 学生表
CREATE TABLE icps_stu (
    stu_card_no    VARCHAR(50)  PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    sno            VARCHAR(20)  NOT NULL,
    sname          VARCHAR(50)  NOT NULL,
    ssex           INT          DEFAULT NULL,
    sage           INT          DEFAULT NULL,
    stu_address    VARCHAR(200) DEFAULT NULL,
    shbt           VARCHAR(100) DEFAULT NULL,
    sblood         VARCHAR(10)  DEFAULT NULL,
    start_sign     VARCHAR(10)  DEFAULT NULL,
    evaluated_type VARCHAR(20)  DEFAULT NULL,
    stu_dept       VARCHAR(50)  DEFAULT NULL,
    stu_major      VARCHAR(50)  DEFAULT NULL,
    stu_clazz      VARCHAR(50)  DEFAULT NULL,
    region         VARCHAR(50)  DEFAULT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    deleted        TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_stu_user_id UNIQUE (user_id),
    CONSTRAINT uk_stu_sno UNIQUE (sno)
);
CREATE INDEX idx_stu_sname ON icps_stu (sname);
CREATE INDEX idx_stu_dept ON icps_stu (stu_dept);

-- 教师表
CREATE TABLE icps_teacher (
    user_id          BIGINT       PRIMARY KEY,
    teacher_card_no  VARCHAR(50)  NOT NULL,
    teacher_name     VARCHAR(50)  NOT NULL,
    dept             VARCHAR(50)  DEFAULT NULL,
    title            VARCHAR(50)  DEFAULT NULL,
    email            VARCHAR(100) DEFAULT NULL,
    phone            VARCHAR(20)  DEFAULT NULL,
    status           INT          DEFAULT 1,
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    deleted          TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_teacher_card_no UNIQUE (teacher_card_no)
);
CREATE INDEX idx_teacher_name ON icps_teacher (teacher_name);
CREATE INDEX idx_teacher_dept ON icps_teacher (dept);

-- 课程表
CREATE TABLE icps_course (
    course_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code   VARCHAR(20)  NOT NULL,
    course_name   VARCHAR(100) NOT NULL,
    credit        INT          DEFAULT NULL,
    hours         INT          DEFAULT NULL,
    teacher_id    BIGINT       DEFAULT NULL,
    teacher_name  VARCHAR(50)  DEFAULT NULL,
    classroom     VARCHAR(50)  DEFAULT NULL,
    semester      VARCHAR(20)  DEFAULT NULL,
    academic_year VARCHAR(20)  DEFAULT NULL,
    schedule      VARCHAR(100) DEFAULT NULL,
    status        INT          DEFAULT 1,
    capacity      INT          DEFAULT NULL,
    enrolled      INT          DEFAULT 0,
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    deleted       TINYINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_course_code UNIQUE (course_code)
);
CREATE INDEX idx_course_name ON icps_course (course_name);
CREATE INDEX idx_course_teacher ON icps_course (teacher_id);
CREATE INDEX idx_course_semester ON icps_course (semester);

-- 学生选课表
CREATE TABLE icps_student_course (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stu_card_no   VARCHAR(50)   NOT NULL,
    course_id     BIGINT        NOT NULL,
    grade         DECIMAL(4, 1) DEFAULT NULL,
    grade_point   DECIMAL(3, 2) DEFAULT NULL,
    academic_year VARCHAR(20)   DEFAULT NULL,
    semester      VARCHAR(20)   DEFAULT NULL,
    status        INT           DEFAULT 1,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    deleted       TINYINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_stu_course UNIQUE (stu_card_no, course_id, academic_year, semester)
);
CREATE INDEX idx_sc_stu ON icps_student_course (stu_card_no);
CREATE INDEX idx_sc_course ON icps_student_course (course_id);
