-- V99 迁移：把 icps_user.AUTO_INCREMENT 调到安全值，避开学生 user_id 保留段
--
-- 背景：icps_user.user_id 为 AUTO_INCREMENT，学生档案 user_id 落在
--       2023001011..2023001020（且后续新建学生继续该段）。若 AUTO_INCREMENT 自然增长
--       落入该段，新建的非学生用户会与 icps_stu.user_id 撞车，经
--       SecurityUtils.canAccessStudent（按 user_id 比对）误判为本人而接管真实学生
--       档案——水平越权。本会话测试中已实际触发过一次（新建用户被分配 2023001014，
--       撞上学生"赵六111"，误删后已恢复）。
--
-- 做法：把 AUTO_INCREMENT 调到 2023002001（远高于学生段上界 2023001099，
--       给后续新建学生留出 88 个余量），后续非学生用户 auto 值不会再落入学生段。
--       学生登录账号（user_id 2023001011..2023001020）不受影响，仍可正常登录。
--
-- 安全性：ALTER TABLE ... AUTO_INCREMENT 仅调整表元数据，不改动已有行；
--         MySQL 会保证新值 > 当前最大已用 user_id（否则 MySQL 自身会取 max+1）。
--         本脚本可重放（重复执行安全，只会把值推得更高，不影响功能）。
--
-- 适用：经 mysql CLI 执行，或经本仓库 run_v3.py 类似脚本执行。
-- 注意：本脚本针对生产 MySQL 库；H2 测试库不执行此脚本（见 schema-h2.sql 用
--       GENERATED BY DEFAULT AS IDENTITY，测试种子数据已显式指定 user_id）。

-- 取当前 icps_user 最大 user_id 与拟设安全值（2023002001）的较大者，保证不回退
SELECT GREATEST(IFNULL((SELECT MAX(user_id) FROM icps_user), 0), 2023002001)
  INTO @safe_ai;
SET @sql = CONCAT('ALTER TABLE icps_user AUTO_INCREMENT = ', @safe_ai);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
